using Microsoft.EntityFrameworkCore;
using MiniPay.Data;
using MiniPay.Models;

namespace MiniPay.Services;

/// <summary>
/// Dịch vụ Quản lý Công văn Đề nghị Gia hạn Thư Bảo lãnh Thanh toán Ngân hàng (Bank Guarantee Extension Dispatch Management).
/// Tương ứng khối Pmt_GrtClaimExt, Pmt_GrtClaimExtDtl và FrmQLCVanGiaHan_PhatHanhBL, FrmTaoCVanGiaHan_PhatHanhBL, CR_ClaimPM trong BizHTC.Payment.
/// </summary>
public sealed class GuaranteeExtensionService(AppDbContext db)
{
    /// <summary>
    /// Lập công văn đề nghị gia hạn bảo lãnh mới (Pmt_GrtClaimExt_Save_New20200522 / FrmTaoCVanGiaHan_PhatHanhBL).
    /// </summary>
    public async Task<GuaranteeExtensionDispatch> CreateDispatchAsync(
        Guid orgId,
        string? dispatchNo,
        string dealerCode,
        string? dealerName,
        string bankCode,
        string? bankName,
        string? bankCodeMonitor,
        string flagIsHTC,
        int numberOfDaysExt,
        string? remark,
        string? createdBy,
        List<GuaranteeExtensionItemInputDto> items)
    {
        if (string.IsNullOrWhiteSpace(dealerCode))
            throw new ArgumentException("Mã đại lý (DealerCode) không được để trống.");
        if (string.IsNullOrWhiteSpace(bankCode))
            throw new ArgumentException("Mã ngân hàng phát hành bảo lãnh (BankCode) không được để trống.");
        if (numberOfDaysExt <= 0)
            throw new ArgumentException("Số ngày đề nghị gia hạn bảo lãnh phải > 0 ngày.");
        if (items == null || items.Count == 0)
            throw new ArgumentException("Công văn gia hạn bảo lãnh cần ít nhất 1 dòng xe.");

        var finalNo = string.IsNullOrWhiteSpace(dispatchNo)
            ? $"CVGH-{DateTime.Now:yyyyMMdd}-{Random.Shared.Next(100, 999)}"
            : dispatchNo.Trim().ToUpper();

        var exists = await db.GuaranteeExtensionDispatches.AnyAsync(d => d.OrgId == orgId && d.DispatchNo == finalNo);
        if (exists)
            throw new InvalidOperationException($"Số công văn đề nghị gia hạn '{finalNo}' đã tồn tại trên hệ thống.");

        var vinSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var it in items)
        {
            if (string.IsNullOrWhiteSpace(it.VIN))
                throw new ArgumentException("Số khung xe (VIN) không được để trống.");
            if (!vinSet.Add(it.VIN.Trim().ToUpper()))
                throw new ArgumentException($"Số khung VIN '{it.VIN}' bị trùng lặp trong cùng công văn.");
        }

        var details = new List<GuaranteeExtensionDetail>();
        foreach (var item in items)
        {
            var detail = BuildDetailItem(orgId, item, numberOfDaysExt);
            details.Add(detail);
        }

        var dispatch = new GuaranteeExtensionDispatch
        {
            OrgId = orgId,
            DispatchNo = finalNo,
            DealerCode = dealerCode.Trim().ToUpper(),
            DealerName = string.IsNullOrWhiteSpace(dealerName) ? dealerCode.Trim().ToUpper() : dealerName.Trim(),
            BankCode = bankCode.Trim().ToUpper(),
            BankName = string.IsNullOrWhiteSpace(bankName) ? ResolveBankName(bankCode) : bankName.Trim(),
            BankCodeMonitor = bankCodeMonitor?.Trim().ToUpper(),
            FlagIsHTC = string.IsNullOrWhiteSpace(flagIsHTC) ? "1" : flagIsHTC.Trim(),
            NumberOfDaysExt = numberOfDaysExt,
            TotalCarCount = details.Count,
            TotalAmount = details.Sum(d => d.GrtValue),
            TotalCarsNotDelivered = details.Count(d => !d.IsDelivered),
            TotalCarsDelivered = details.Count(d => d.IsDelivered),
            Status = GuaranteeExtensionStatus.Draft,
            SignCAStatus = ExtensionSignCAStatus.Pending,
            Remark = remark?.Trim(),
            CreatedBy = string.IsNullOrWhiteSpace(createdBy) ? "ChuyenVienTinDungHTC" : createdBy.Trim(),
            CreatedAt = DateTime.Now,
            Details = details
        };

        db.GuaranteeExtensionDispatches.Add(dispatch);
        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Tự động quét các bảo lãnh ngân hàng sắp hết hạn và tạo công văn gia hạn (Pmt_GrtClaimExt_GenAuto_New20201210).
    /// </summary>
    public async Task<List<GuaranteeExtensionDispatch>> AutoGenerateDispatchesAsync(
        Guid orgId,
        int withinDays = 15,
        int numberOfDaysExt = 30,
        string flagIsHTC = "1",
        string? remark = "Hệ thống tự động sinh công văn gia hạn bảo lãnh định kỳ",
        string? createdBy = "AutoScheduleService")
    {
        var targetDate = DateTime.Today.AddDays(withinDays);

        // Lấy danh sách các bảo lãnh đang có hiệu lực và sắp hết hạn
        var activeGuarantees = await db.Guarantees
            .Include(g => g.Details)
            .Where(g => g.OrgId == orgId &&
                        g.Status == GuaranteeStatus.Active &&
                        g.DateExpired <= targetDate)
            .ToListAsync();

        if (activeGuarantees.Count == 0)
            return [];

        // Nhóm theo Ngân hàng và Đại lý
        var grouped = activeGuarantees.GroupBy(g => new { g.BankCode, g.PartnerCode });
        var createdList = new List<GuaranteeExtensionDispatch>();

        foreach (var group in grouped)
        {
            var bankCode = group.Key.BankCode;
            var dealerCode = group.Key.PartnerCode;
            var firstGrt = group.First();

            var finalNo = $"CVGH-AUTO-{DateTime.Now:yyyyMMdd}-{Random.Shared.Next(100, 999)}";

            var items = new List<GuaranteeExtensionDetail>();
            foreach (var grt in group)
            {
                foreach (var dtl in grt.Details.Where(d => d.Status == GuaranteeDetailStatus.Active))
                {
                    var expDate = grt.DateExpired;
                    var newExpDate = expDate.AddDays(numberOfDaysExt);

                    items.Add(new GuaranteeExtensionDetail
                    {
                        OrgId = orgId,
                        CarId = dtl.ItemRefNo,
                        VIN = !string.IsNullOrWhiteSpace(dtl.ItemRefNo) && dtl.ItemRefNo.Length >= 10 ? dtl.ItemRefNo : $"KMHCT81EPHU{Random.Shared.Next(100000, 999999)}",
                        ModelCode = "SANTAFE-CALLI",
                        ModelName = !string.IsNullOrWhiteSpace(dtl.Description) ? dtl.Description : "Hyundai Santa Fe Calligraphy",
                        SpecCode = "STD",
                        SpecDescription = "Bản tiêu chuẩn phân phối HTC",
                        ColorName = "Trắng Tinh Khôi",
                        SOCode = grt.ContractNo,
                        DlrCtrNo = grt.ContractNo,
                        GuaranteeNo = grt.GuaranteeNo,
                        BankGuaranteeNo = grt.BankGuaranteeNo,
                        GrtDateStart = grt.DateOpen,
                        GrtDateExpired = expDate,
                        ExtendedDate = newExpDate,
                        GrtValue = dtl.GuaranteeValue > 0 ? dtl.GuaranteeValue : 1_000_000_000,
                        UnitPrice = dtl.OrderAmount > 0 ? dtl.OrderAmount : 1_250_000_000,
                        IsDelivered = false,
                        Status = GuaranteeExtensionDetailStatus.Pending,
                        Remark = "Quét tự động từ hệ thống bảo lãnh HTC"
                    });
                }
            }

            if (items.Count == 0) continue;

            var dispatch = new GuaranteeExtensionDispatch
            {
                OrgId = orgId,
                DispatchNo = finalNo,
                DealerCode = dealerCode,
                DealerName = firstGrt.PartnerName ?? dealerCode,
                BankCode = bankCode,
                BankName = firstGrt.BankName ?? ResolveBankName(bankCode),
                FlagIsHTC = flagIsHTC,
                NumberOfDaysExt = numberOfDaysExt,
                TotalCarCount = items.Count,
                TotalAmount = items.Sum(d => d.GrtValue),
                TotalCarsNotDelivered = items.Count(d => !d.IsDelivered),
                TotalCarsDelivered = items.Count(d => d.IsDelivered),
                Status = GuaranteeExtensionStatus.Draft,
                SignCAStatus = ExtensionSignCAStatus.Pending,
                Remark = remark,
                CreatedBy = createdBy,
                CreatedAt = DateTime.Now,
                Details = items
            };

            db.GuaranteeExtensionDispatches.Add(dispatch);
            createdList.Add(dispatch);
        }

        await db.SaveChangesAsync();
        return createdList;
    }

    /// <summary>
    /// Ký số điện tử CA và phát hành công văn (Pmt_GrtClaimExt_SignAndSendEmail / FrmQLCVanGiaHan_PhatHanhBL.btnKyDienTu).
    /// </summary>
    public async Task<GuaranteeExtensionDispatch?> SignCAAsync(long id, Guid orgId, string? signerName, string? filePath)
    {
        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);

        if (dispatch == null) return null;

        if (dispatch.Status != GuaranteeExtensionStatus.Draft && dispatch.Status != GuaranteeExtensionStatus.PendingSign)
            throw new InvalidOperationException($"Chỉ có thể ký số công văn ở trạng thái Mới tạo (Draft) hoặc Chờ ký (PendingSign). Trạng thái hiện tại: {dispatch.Status}.");

        dispatch.SignCAStatus = ExtensionSignCAStatus.Signed;
        dispatch.Status = GuaranteeExtensionStatus.Signed;
        dispatch.SignedBy = string.IsNullOrWhiteSpace(signerName) ? "NguyenVanHieu_TongGiamDoc_HTV" : signerName.Trim();
        dispatch.SignedAt = DateTime.Now;
        dispatch.CertThumbprint = Guid.NewGuid().ToString("N").ToUpper()[..16];
        dispatch.FilePath = string.IsNullOrWhiteSpace(filePath) ? $"/documents/extension/{dispatch.DispatchNo}-Signed.pdf" : filePath.Trim();

        foreach (var dtl in dispatch.Details)
        {
            dtl.Status = GuaranteeExtensionDetailStatus.Active;
        }

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Ghi nhận ngân hàng phát hành chấp thuận gia hạn thời hạn Thư bảo lãnh và đồng bộ cập nhật ngày hết hạn mới.
    /// </summary>
    public async Task<GuaranteeExtensionDispatch?> BankAcceptAsync(long id, Guid orgId, string bankResponseRef, string? note)
    {
        if (string.IsNullOrWhiteSpace(bankResponseRef))
            throw new ArgumentException("Số công văn / thông báo chấp thuận của ngân hàng không được để trống.");

        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);

        if (dispatch == null) return null;

        if (dispatch.Status != GuaranteeExtensionStatus.Signed)
            throw new InvalidOperationException($"Chỉ có thể ghi nhận ngân hàng chấp thuận khi công văn đã được ký số (Signed). Trạng thái hiện tại: {dispatch.Status}.");

        dispatch.Status = GuaranteeExtensionStatus.BankAccepted;
        dispatch.BankResponseRef = bankResponseRef.Trim();
        dispatch.BankAcceptedAt = DateTime.Now;
        if (!string.IsNullOrWhiteSpace(note))
            dispatch.Remark = string.IsNullOrWhiteSpace(dispatch.Remark) ? note.Trim() : $"{dispatch.Remark} | {note.Trim()}";

        foreach (var dtl in dispatch.Details)
        {
            dtl.Status = GuaranteeExtensionDetailStatus.BankAccepted;

            // Đồng bộ cập nhật ngày hết hạn mới cho Thư bảo lãnh gốc trên hệ thống
            if (!string.IsNullOrWhiteSpace(dtl.BankGuaranteeNo))
            {
                var relatedGuarantees = await db.Guarantees
                    .Where(g => g.OrgId == orgId && g.BankGuaranteeNo == dtl.BankGuaranteeNo)
                    .ToListAsync();

                foreach (var g in relatedGuarantees)
                {
                    if (g.DateExpired < dtl.ExtendedDate)
                    {
                        g.DateExpired = dtl.ExtendedDate;
                        g.DateEnd = dtl.ExtendedDate;
                    }
                }
            }
        }

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Ghi nhận ngân hàng từ chối gia hạn bảo lãnh kèm lý do.
    /// </summary>
    public async Task<GuaranteeExtensionDispatch?> BankRejectAsync(long id, Guid orgId, string reason)
    {
        if (string.IsNullOrWhiteSpace(reason))
            throw new ArgumentException("Lý do ngân hàng từ chối gia hạn không được để trống.");

        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);

        if (dispatch == null) return null;

        if (dispatch.Status != GuaranteeExtensionStatus.Signed)
            throw new InvalidOperationException($"Chỉ có thể ghi nhận từ chối khi công văn đã được ký và gửi ngân hàng (Signed). Trạng thái hiện tại: {dispatch.Status}.");

        dispatch.Status = GuaranteeExtensionStatus.BankRejected;
        dispatch.BankRejectReason = reason.Trim();

        foreach (var dtl in dispatch.Details)
        {
            dtl.Status = GuaranteeExtensionDetailStatus.BankRejected;
        }

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Hủy công văn gia hạn bảo lãnh (Pmt_GrtClaimExt_Cancel / FrmQLCVanGiaHan_PhatHanhBL.btnDelete).
    /// </summary>
    public async Task<GuaranteeExtensionDispatch?> CancelDispatchAsync(long id, Guid orgId, string? reason)
    {
        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);

        if (dispatch == null) return null;

        if (dispatch.Status == GuaranteeExtensionStatus.BankAccepted)
            throw new InvalidOperationException("Không thể hủy công văn khi ngân hàng đã chính thức chấp thuận gia hạn.");

        dispatch.Status = GuaranteeExtensionStatus.Cancelled;
        dispatch.CancelledAt = DateTime.Now;
        if (!string.IsNullOrWhiteSpace(reason))
            dispatch.Remark = string.IsNullOrWhiteSpace(dispatch.Remark) ? reason.Trim() : $"{dispatch.Remark} | Hủy: {reason.Trim()}";

        foreach (var dtl in dispatch.Details)
        {
            dtl.Status = GuaranteeExtensionDetailStatus.Cancelled;
        }

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Bổ sung xe vào công văn đang ở trạng thái Draft.
    /// </summary>
    public async Task<GuaranteeExtensionDispatch> AddVehiclesAsync(long id, Guid orgId, List<GuaranteeExtensionItemInputDto> items)
    {
        if (items == null || items.Count == 0)
            throw new ArgumentException("Cần danh sách xe để bổ sung vào công văn.");

        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId)
            ?? throw new InvalidOperationException($"Không tìm thấy công văn #{id}.");

        if (dispatch.Status != GuaranteeExtensionStatus.Draft)
            throw new InvalidOperationException("Chỉ có thể bổ sung xe khi công văn ở trạng thái Mới tạo (Draft).");

        var existingVins = new HashSet<string>(dispatch.Details.Select(d => d.VIN), StringComparer.OrdinalIgnoreCase);

        foreach (var item in items)
        {
            if (string.IsNullOrWhiteSpace(item.VIN)) continue;
            var vinUpper = item.VIN.Trim().ToUpper();
            if (existingVins.Contains(vinUpper)) continue;
            existingVins.Add(vinUpper);

            var detail = BuildDetailItem(orgId, item, dispatch.NumberOfDaysExt);
            dispatch.Details.Add(detail);
        }

        dispatch.TotalCarCount = dispatch.Details.Count;
        dispatch.TotalAmount = dispatch.Details.Sum(d => d.GrtValue);
        dispatch.TotalCarsNotDelivered = dispatch.Details.Count(d => !d.IsDelivered);
        dispatch.TotalCarsDelivered = dispatch.Details.Count(d => d.IsDelivered);

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Xóa 1 xe khỏi công văn đang ở trạng thái Draft.
    /// </summary>
    public async Task<GuaranteeExtensionDispatch> RemoveVehicleAsync(long id, long detailId, Guid orgId)
    {
        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId)
            ?? throw new InvalidOperationException($"Không tìm thấy công văn #{id}.");

        if (dispatch.Status != GuaranteeExtensionStatus.Draft)
            throw new InvalidOperationException("Chỉ có thể xóa xe khi công văn ở trạng thái Mới tạo (Draft).");

        var detail = dispatch.Details.FirstOrDefault(d => d.Id == detailId)
            ?? throw new InvalidOperationException($"Không tìm thấy dòng xe #{detailId} trong công văn.");

        dispatch.Details.Remove(detail);
        db.GuaranteeExtensionDetails.Remove(detail);

        dispatch.TotalCarCount = dispatch.Details.Count;
        dispatch.TotalAmount = dispatch.Details.Sum(d => d.GrtValue);
        dispatch.TotalCarsNotDelivered = dispatch.Details.Count(d => !d.IsDelivered);
        dispatch.TotalCarsDelivered = dispatch.Details.Count(d => d.IsDelivered);

        await db.SaveChangesAsync();
        return dispatch;
    }

    /// <summary>
    /// Xóa nháp công văn gia hạn chưa ký số.
    /// </summary>
    public async Task DeleteDraftAsync(long id, Guid orgId)
    {
        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId)
            ?? throw new InvalidOperationException($"Không tìm thấy công văn #{id}.");

        if (dispatch.Status != GuaranteeExtensionStatus.Draft && dispatch.Status != GuaranteeExtensionStatus.Cancelled)
            throw new InvalidOperationException("Chỉ có thể xóa công văn ở trạng thái Mới tạo (Draft) hoặc Đã hủy (Cancelled).");

        if (dispatch.SignCAStatus == ExtensionSignCAStatus.Signed)
            throw new InvalidOperationException("Không thể xóa công văn đã được ký số điện tử CA.");

        db.GuaranteeExtensionDetails.RemoveRange(dispatch.Details);
        db.GuaranteeExtensionDispatches.Remove(dispatch);
        await db.SaveChangesAsync();
    }

    /// <summary>
    /// Lấy danh sách công văn kèm bộ lọc (Pmt_GrtClaimExt_Get).
    /// </summary>
    public async Task<List<GuaranteeExtensionDispatch>> GetDispatchesAsync(
        Guid orgId,
        string? dealerCode = null,
        string? bankCode = null,
        string? status = null,
        string? flagIsHTC = null,
        string? vin = null)
    {
        var query = db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .Where(d => d.OrgId == orgId)
            .AsQueryable();

        if (!string.IsNullOrWhiteSpace(dealerCode))
            query = query.Where(d => d.DealerCode == dealerCode.Trim().ToUpper());

        if (!string.IsNullOrWhiteSpace(bankCode))
            query = query.Where(d => d.BankCode == bankCode.Trim().ToUpper());

        if (!string.IsNullOrWhiteSpace(status) && Enum.TryParse<GuaranteeExtensionStatus>(status, true, out var st))
            query = query.Where(d => d.Status == st);

        if (!string.IsNullOrWhiteSpace(flagIsHTC))
            query = query.Where(d => d.FlagIsHTC == flagIsHTC.Trim());

        if (!string.IsNullOrWhiteSpace(vin))
        {
            var vinUpper = vin.Trim().ToUpper();
            query = query.Where(d => d.Details.Any(dt => dt.VIN.Contains(vinUpper)));
        }

        return await query.OrderByDescending(d => d.CreatedAt).ToListAsync();
    }

    /// <summary>
    /// Lấy chi tiết 1 công văn kèm danh sách xe.
    /// </summary>
    public async Task<GuaranteeExtensionDispatch?> GetDispatchByIdAsync(long id, Guid orgId)
    {
        return await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);
    }

    /// <summary>
    /// Sinh mẫu in Công văn đề nghị gia hạn thời hạn Thư bảo lãnh (CR_ClaimPM Advice) chuẩn ngân hàng kèm đọc số tiền bằng chữ tiếng Việt.
    /// </summary>
    public async Task<DispatchAdviceDto?> GenerateDispatchAdviceAsync(long id, Guid orgId)
    {
        var dispatch = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .FirstOrDefaultAsync(d => d.Id == id && d.OrgId == orgId);

        if (dispatch == null) return null;

        var amountInWords = NumberToVietnameseText(dispatch.TotalAmount);
        var phapNhan = dispatch.FlagIsHTC == "2" ? "CÔNG TY CỔ PHẦN HYUNDAI THÀNH CÔNG THƯƠNG MẠI (HTV)" : "CÔNG TY CỔ PHẦN HYUNDAI THÀNH CÔNG VIỆT NAM (HTC)";
        var subNo = dispatch.FlagIsHTC == "2" ? $"{dispatch.DispatchNo}/CV-HTCVN" : $"{dispatch.DispatchNo}/CV-HTC";

        return new DispatchAdviceDto(
            DispatchNo: dispatch.DispatchNo,
            DispatchSubNo: subNo,
            CompanyLegalName: phapNhan,
            DateCreated: dispatch.CreatedAt.ToString("dd/MM/yyyy"),
            DealerCode: dispatch.DealerCode,
            DealerName: dispatch.DealerName,
            BankCode: dispatch.BankCode,
            BankName: dispatch.BankName,
            BankCodeMonitor: dispatch.BankCodeMonitor ?? "VPBANK_HO",
            NumberOfDaysExt: dispatch.NumberOfDaysExt,
            TotalCarCount: dispatch.TotalCarCount,
            TotalCarsNotDelivered: dispatch.TotalCarsNotDelivered,
            TotalCarsDelivered: dispatch.TotalCarsDelivered,
            TotalAmount: dispatch.TotalAmount,
            AmountInWords: amountInWords,
            Status: dispatch.Status.ToString(),
            SignCAStatus: dispatch.SignCAStatus.ToString(),
            SignedBy: dispatch.SignedBy,
            SignedDate: dispatch.SignedAt?.ToString("dd/MM/yyyy HH:mm"),
            CertThumbprint: dispatch.CertThumbprint,
            BankResponseRef: dispatch.BankResponseRef,
            BankAcceptedDate: dispatch.BankAcceptedAt?.ToString("dd/MM/yyyy HH:mm"),
            BankRejectReason: dispatch.BankRejectReason,
            Remark: dispatch.Remark,
            Vehicles: dispatch.Details.Select(d => new DispatchAdviceVehicleItemDto(
                VIN: d.VIN,
                ModelCode: d.ModelCode,
                ModelName: d.ModelName ?? d.ModelCode,
                SpecDescription: d.SpecDescription ?? "Bản tiêu chuẩn",
                ColorName: d.ColorName ?? "Tiêu chuẩn",
                DlrCtrNo: d.DlrCtrNo ?? "-",
                BankGuaranteeNo: d.BankGuaranteeNo,
                GrtDateStart: d.GrtDateStart.ToString("dd/MM/yyyy"),
                GrtDateExpired: d.GrtDateExpired.ToString("dd/MM/yyyy"),
                ExtendedDate: d.ExtendedDate.ToString("dd/MM/yyyy"),
                GrtValue: d.GrtValue,
                UnitPrice: d.UnitPrice,
                IsDelivered: d.IsDelivered,
                DeliveryStatusText: d.IsDelivered ? "Đã bàn giao xe" : "Chưa giao xe (Chờ hồ sơ)"
            )).ToList()
        );
    }

    /// <summary>
    /// Báo cáo thống kê tổng hợp dashboard công văn gia hạn bảo lãnh.
    /// </summary>
    public async Task<GuaranteeExtensionSummaryDto> GetSummaryAsync(Guid orgId)
    {
        var dispatches = await db.GuaranteeExtensionDispatches
            .Include(d => d.Details)
            .Where(d => d.OrgId == orgId)
            .ToListAsync();

        int totalCount = dispatches.Count;
        int draftCount = dispatches.Count(d => d.Status == GuaranteeExtensionStatus.Draft);
        int signedCount = dispatches.Count(d => d.Status == GuaranteeExtensionStatus.Signed);
        int acceptedCount = dispatches.Count(d => d.Status == GuaranteeExtensionStatus.BankAccepted);
        int rejectedCount = dispatches.Count(d => d.Status == GuaranteeExtensionStatus.BankRejected);
        int cancelledCount = dispatches.Count(d => d.Status == GuaranteeExtensionStatus.Cancelled);

        long totalGuaranteeAmount = dispatches.Where(d => d.Status != GuaranteeExtensionStatus.Cancelled).Sum(d => d.TotalAmount);
        long acceptedGuaranteeAmount = dispatches.Where(d => d.Status == GuaranteeExtensionStatus.BankAccepted).Sum(d => d.TotalAmount);

        int totalVehicles = dispatches.Where(d => d.Status != GuaranteeExtensionStatus.Cancelled).Sum(d => d.TotalCarCount);
        int vehiclesNotDelivered = dispatches.Where(d => d.Status != GuaranteeExtensionStatus.Cancelled).Sum(d => d.TotalCarsNotDelivered);

        var byBank = dispatches
            .Where(d => d.Status != GuaranteeExtensionStatus.Cancelled)
            .GroupBy(d => d.BankCode)
            .Select(g => new BankGuaranteeExtSummaryItem(
                BankCode: g.Key,
                BankName: g.First().BankName,
                DispatchCount: g.Count(),
                CarCount: g.Sum(x => x.TotalCarCount),
                TotalAmount: g.Sum(x => x.TotalAmount),
                AcceptedCount: g.Count(x => x.Status == GuaranteeExtensionStatus.BankAccepted)
            ))
            .ToList();

        return new GuaranteeExtensionSummaryDto(
            TotalDispatches: totalCount,
            DraftCount: draftCount,
            SignedCount: signedCount,
            AcceptedCount: acceptedCount,
            RejectedCount: rejectedCount,
            CancelledCount: cancelledCount,
            TotalGuaranteeAmount: totalGuaranteeAmount,
            AcceptedGuaranteeAmount: acceptedGuaranteeAmount,
            TotalVehicles: totalVehicles,
            VehiclesNotDelivered: vehiclesNotDelivered,
            ByBank: byBank
        );
    }

    private static GuaranteeExtensionDetail BuildDetailItem(Guid orgId, GuaranteeExtensionItemInputDto item, int numberOfDaysExt)
    {
        var startDate = item.GrtDateStart ?? DateTime.Today.AddDays(-30);
        var expiredDate = item.GrtDateExpired ?? startDate.AddDays(45);
        var extendedDate = item.ExtendedDate ?? expiredDate.AddDays(numberOfDaysExt);
        var grtValue = item.GrtValue > 0 ? item.GrtValue : (item.UnitPrice > 0 ? (long)(item.UnitPrice * 0.85) : 800_000_000);
        var unitPrice = item.UnitPrice > 0 ? item.UnitPrice : (long)(grtValue / 0.85);

        return new GuaranteeExtensionDetail
        {
            OrgId = orgId,
            CarId = item.CarId?.Trim(),
            VIN = item.VIN.Trim().ToUpper(),
            ModelCode = string.IsNullOrWhiteSpace(item.ModelCode) ? "SANTAFE-CALLI" : item.ModelCode.Trim().ToUpper(),
            ModelName = item.ModelName?.Trim(),
            SpecCode = item.SpecCode?.Trim(),
            SpecDescription = item.SpecDescription?.Trim(),
            ColorName = item.ColorName?.Trim() ?? "Trắng Tinh Khôi",
            SOCode = item.SOCode?.Trim(),
            DlrCtrNo = item.DlrCtrNo?.Trim(),
            GuaranteeNo = item.GuaranteeNo?.Trim(),
            BankGuaranteeNo = string.IsNullOrWhiteSpace(item.BankGuaranteeNo) ? $"BL-{item.VIN[..Math.Min(8, item.VIN.Length)]}" : item.BankGuaranteeNo.Trim(),
            GrtDateStart = startDate,
            GrtDateExpired = expiredDate,
            ExtendedDate = extendedDate,
            GrtValue = grtValue,
            UnitPrice = unitPrice,
            IsDelivered = item.IsDelivered,
            DeliveryDate = item.DeliveryDate,
            Status = GuaranteeExtensionDetailStatus.Pending,
            Remark = item.Remark?.Trim()
        };
    }

    private static string ResolveBankName(string code) => code.ToUpperInvariant() switch
    {
        "VPB" or "VPBANK" => "Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)",
        "CTG" or "VIETINBANK" => "Ngân hàng TMCP Công Thương Việt Nam (VietinBank)",
        "TCB" or "TECHCOMBANK" => "Ngân hàng TMCP Kỹ Thương Việt Nam (Techcombank)",
        "MBB" or "MBBANK" => "Ngân hàng TMCP Quân Đội (MBBank)",
        "VCB" or "VIETCOMBANK" => "Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)",
        "BIDV" => "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)",
        _ => $"Ngân hàng đối tác {code}"
    };

    /// <summary>
    /// Đọc số tiền thành chữ tiếng Việt tài chính chuẩn.
    /// </summary>
    public static string NumberToVietnameseText(long number)
    {
        if (number == 0) return "Không đồng";
        if (number < 0) return "Âm " + NumberToVietnameseText(-number);

        string[] units = { "", "nghìn", "triệu", "tỷ", "nghìn tỷ", "triệu tỷ" };
        string sNumber = number.ToString();
        var groups = new List<string>();

        while (sNumber.Length > 0)
        {
            int take = Math.Min(3, sNumber.Length);
            groups.Insert(0, sNumber[^take..]);
            sNumber = sNumber[..^take];
        }

        var result = "";
        for (int i = 0; i < groups.Count; i++)
        {
            int groupValue = int.Parse(groups[i]);
            if (groupValue > 0)
            {
                string groupText = ThreeDigitsToText(groupValue, i > 0);
                int unitIndex = groups.Count - 1 - i;
                result += groupText + " " + units[unitIndex] + " ";
            }
        }

        result = result.Trim();
        if (!string.IsNullOrEmpty(result))
        {
            result = char.ToUpper(result[0]) + result[1..] + " đồng chẵn.";
        }
        return result;
    }

    private static string ThreeDigitsToText(int number, bool hasHigherGroup)
    {
        string[] digits = { "không", "một", "hai", "ba", "bốn", "năm", "sáu", "bảy", "tám", "chín" };
        int hundreds = number / 100;
        int tens = (number % 100) / 10;
        int ones = number % 10;

        string result = "";
        if (hundreds > 0 || hasHigherGroup)
        {
            result += digits[hundreds] + " trăm ";
        }

        if (tens > 1)
        {
            result += digits[tens] + " mươi ";
            if (ones == 1) result += "mốt ";
            else if (ones == 5) result += "lăm ";
            else if (ones > 0) result += digits[ones] + " ";
        }
        else if (tens == 1)
        {
            result += "mười ";
            if (ones == 5) result += "lăm ";
            else if (ones > 0) result += digits[ones] + " ";
        }
        else if (tens == 0)
        {
            if (hundreds > 0 || hasHigherGroup)
            {
                if (ones > 0) result += "linh " + digits[ones] + " ";
            }
            else if (ones > 0)
            {
                result += digits[ones] + " ";
            }
        }

        return result.TrimEnd();
    }
}

public record GuaranteeExtensionItemInputDto(
    string VIN,
    string? CarId,
    string? ModelCode,
    string? ModelName,
    string? SpecCode,
    string? SpecDescription,
    string? ColorName,
    string? SOCode,
    string? DlrCtrNo,
    string? GuaranteeNo,
    string? BankGuaranteeNo,
    DateTime? GrtDateStart,
    DateTime? GrtDateExpired,
    DateTime? ExtendedDate,
    long GrtValue,
    long UnitPrice,
    bool IsDelivered,
    DateTime? DeliveryDate,
    string? Remark
);

public record DispatchAdviceVehicleItemDto(
    string VIN,
    string ModelCode,
    string ModelName,
    string SpecDescription,
    string ColorName,
    string DlrCtrNo,
    string BankGuaranteeNo,
    string GrtDateStart,
    string GrtDateExpired,
    string ExtendedDate,
    long GrtValue,
    long UnitPrice,
    bool IsDelivered,
    string DeliveryStatusText
);

public record DispatchAdviceDto(
    string DispatchNo,
    string DispatchSubNo,
    string CompanyLegalName,
    string DateCreated,
    string DealerCode,
    string DealerName,
    string BankCode,
    string BankName,
    string BankCodeMonitor,
    int NumberOfDaysExt,
    int TotalCarCount,
    int TotalCarsNotDelivered,
    int TotalCarsDelivered,
    long TotalAmount,
    string AmountInWords,
    string Status,
    string SignCAStatus,
    string? SignedBy,
    string? SignedDate,
    string? CertThumbprint,
    string? BankResponseRef,
    string? BankAcceptedDate,
    string? BankRejectReason,
    string? Remark,
    List<DispatchAdviceVehicleItemDto> Vehicles
);

public record BankGuaranteeExtSummaryItem(
    string BankCode,
    string BankName,
    int DispatchCount,
    int CarCount,
    long TotalAmount,
    int AcceptedCount
);

public record GuaranteeExtensionSummaryDto(
    int TotalDispatches,
    int DraftCount,
    int SignedCount,
    int AcceptedCount,
    int RejectedCount,
    int CancelledCount,
    long TotalGuaranteeAmount,
    long AcceptedGuaranteeAmount,
    int TotalVehicles,
    int VehiclesNotDelivered,
    List<BankGuaranteeExtSummaryItem> ByBank
);
